import { format } from "date-fns";

import type { Appointment } from "./types";

export function buildSeedAppointments(): Appointment[] {
  const today = format(new Date(), "yyyy-MM-dd");
  return [
    {
      id: "1",
      date: today,
      time: "08:00 AM",
      patientName: "Sarah Jenkins",
      room: "RM 1",
      stage: "PREVISIT",
      reason: "Post-Hospital Follow-up (CHF Exacerbation)",
      appointmentType: "Post-Acute Follow-up",
      estimatedDurationMins: 60,
      pcp: "Dr. Ellis",
      navigator: "Anna",
      formCompletionStatus: "In Progress",
      missingFormNames: [
        "Medical History",
        "Consent To Treat",
        "Insurance Card Photo",
      ],
      formsCompleteCount: 2,
      formsTotalCount: 4,
      huddleTasks: [
        {
          id: "1-h1",
          text: "Order A1C test (Non-diabetic w/ high BMI)",
          completed: false,
        },
        { id: "1-h2", text: "Perform EKG (Recent ER visit)", completed: false },
      ],
    },
    {
      id: "2",
      date: today,
      time: "08:15 AM",
      patientName: "Robert Chen",
      room: "RM 3",
      stage: "INTAKE",
      reason: "Follow-up (Diabetes)",
      appointmentType: "Established Follow-up",
      estimatedDurationMins: 20,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "Not Started",
      missingFormNames: [
        "Medical History",
        "Consent To Treat",
        "Insurance Card Photo",
        "ROS",
      ],
      formsCompleteCount: 0,
      formsTotalCount: 4,
      huddleTasks: [
        {
          id: "2-h1",
          text: "Confirm pharmacy for insulin start",
          completed: false,
        },
        { id: "2-h2", text: "Check foot exam status", completed: false },
      ],
    },
    {
      id: "3",
      date: today,
      time: "08:45 AM",
      patientName: "Elena Rodriguez",
      room: "WAIT",
      stage: "ROOMING",
      reason: "Acute: Cough",
      appointmentType: "Acute Sick Visit",
      estimatedDurationMins: 30,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "In Progress",
      missingFormNames: ["Consent To Treat", "Pharmacy Profile"],
      formsCompleteCount: 2,
      formsTotalCount: 4,
      huddleTasks: [
        { id: "3-h1", text: "Check pulse ox on room air", completed: false },
        { id: "3-h2", text: "Verify home oxygen supply", completed: false },
      ],
    },
    {
      id: "4",
      date: today,
      time: "09:30 AM",
      patientName: "James Wilson",
      room: "RM 2",
      stage: "VISIT",
      reason: "HTN Management",
      appointmentType: "Chronic Care Visit",
      estimatedDurationMins: 30,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "Completed",
      missingFormNames: [],
      formsCompleteCount: 4,
      formsTotalCount: 4,
      huddleTasks: [
        { id: "4-h1", text: "Update BP medication list", completed: false },
        { id: "4-h2", text: "Schedule 3-month follow-up", completed: false },
      ],
    },
    {
      id: "5",
      date: today,
      time: "10:00 AM",
      patientName: "Maria Garcia",
      room: "RM 4",
      stage: "LABS",
      reason: "New Patient Intake",
      appointmentType: "New Patient",
      estimatedDurationMins: 60,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "Not Started",
      missingFormNames: [
        "Medical History",
        "Consent To Treat",
        "Insurance Card Photo",
        "Demographics",
      ],
      formsCompleteCount: 0,
      formsTotalCount: 4,
      huddleTasks: [
        {
          id: "5-h1",
          text: "New Patient: Obtain outside records",
          completed: false,
        },
        { id: "5-h2", text: "Review vaccine history", completed: false },
      ],
    },
    {
      id: "6",
      date: today,
      time: "10:15 AM",
      patientName: "Samuel Lee",
      room: "LAB 1",
      stage: "CARE MANAGEMENT",
      reason: "Blood Work",
      appointmentType: "Lab Draw",
      estimatedDurationMins: 15,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "In Progress",
      missingFormNames: ["Insurance Card Photo"],
      formsCompleteCount: 3,
      formsTotalCount: 4,
      huddleTasks: [
        { id: "6-h1", text: "Lab prep: Fasting check", completed: false },
        {
          id: "6-h2",
          text: "Verify insurance for specialty labs",
          completed: false,
        },
      ],
    },
    {
      id: "7",
      date: today,
      time: "11:00 AM",
      patientName: "Linda Wu",
      room: "WAIT",
      stage: "WRAP UP",
      reason: "Post-Op Check",
      appointmentType: "Procedure Follow-up",
      estimatedDurationMins: 45,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "Completed",
      missingFormNames: [],
      formsCompleteCount: 4,
      formsTotalCount: 4,
      huddleTasks: [
        { id: "7-h1", text: "Post-Op: Check incision site", completed: false },
        { id: "7-h2", text: "Remove sutures", completed: false },
      ],
    },
    {
      id: "8",
      date: today,
      time: "11:30 AM",
      patientName: "David Miller",
      room: "RM 5",
      stage: "VISIT",
      reason: "Immunizations",
      appointmentType: "Nurse Visit",
      estimatedDurationMins: 30,
      pcp: "Dr. Aris",
      navigator: "Anna",
      formCompletionStatus: "In Progress",
      missingFormNames: ["Vaccine History", "Guardian Consent"],
      formsCompleteCount: 2,
      formsTotalCount: 4,
      huddleTasks: [
        {
          id: "8-h1",
          text: "Pediatric: School form signature",
          completed: false,
        },
        { id: "8-h2", text: "Administer flu shot", completed: false },
      ],
    },
  ];
}
