import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppShell } from "@/components/app-shell";
import { TooltipProvider } from "@/components/ui/tooltip";
import { MessagingStoreProvider } from "@/app/messaging/messaging-store";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full antialiased", inter.variable, geistMono.variable)}>
      <body
        className={cn("min-h-full flex flex-col font-sans", inter.variable)}
        suppressHydrationWarning
      >
        <TooltipProvider delayDuration={0}>
          {/* Shared messaging state (conversations, messages, directory)
           * for `/messaging` and the patient profile dialog. Lives here at
           * the root so edits made in one view are visible in the other. */}
          <MessagingStoreProvider>
            <AppShell>{children}</AppShell>
          </MessagingStoreProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
