import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppShell } from "@/components/app-shell";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppointmentsStoreProvider } from "@/app/clinic-flow/appointments-store";
import { MessagingStoreProvider } from "@/app/messaging/messaging-store";
import { PanelTasksStoreProvider } from "@/app/patient-profile/panel-tasks-store";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full antialiased", inter.variable, geistMono.variable)}>
      <body
        className={cn("min-h-full flex flex-col font-sans", inter.variable)}
        suppressHydrationWarning
      >
        <TooltipProvider delayDuration={0}>
          {/* Shared application state lives at the root so edits made in
           * one view propagate to others (e.g. stage/room changes from
           * the patient profile detail are visible in the clinic-flow
           * workspace, and new messages sent from the profile show up
           * under /messaging). */}
          <AppointmentsStoreProvider>
            <MessagingStoreProvider>
              <PanelTasksStoreProvider>
                <AppShell>{children}</AppShell>
              </PanelTasksStoreProvider>
            </MessagingStoreProvider>
          </AppointmentsStoreProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
